server:
  port: 8080 # 애플리케이션 서버가 사용하는 포트를 8080으로 지정

spring:
  jpa:
    show-sql: true # JPA가 생성하는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 포맷하여 보기 좋게 출력
        hbm2ddl:
          auto: create # 애플리케이션 시작 시 데이터베이스 스키마를 자동으로 생성
          # 가능한 값:
          # none: 아무 작업도 수행하지 않음
          # validate: 기존 스키마를 검증
          # update: 기존 스키마를 업데이트
          # create: 기존 스키마를 삭제하고 새로 생성
          # create-drop: 애플리케이션 종료 시 스키마를 삭제
    database: mysql # JPA가 사용할 데이터베이스를 MySQL로 지정

  datasource:
    url: jdbc:mysql://localhost:3306/gangnam # MySQL 데이터베이스의 JDBC URL, 로컬호스트의 gangnam 데이터베이스에 연결
    username: gangnam # 데이터베이스에 연결할 때 사용할 사용자 이름
    password: gangnam # 데이터베이스에 연결할 때 사용할 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
